### ISSUE TITLE
Missing label NotDOSBox in EX08.BAT

### ISSUE THREAD

**Issue by Neotmiren** [LoopZ/V8Power#1]
... also all "not DOSBox" examples work in my DOSBox, just because, by coincidence, I have changed COMSPEC variable in dosbox.conf to the path of FreeDOS command.com

The problem is not DOSBox emulator, but its command.com equivalent. It does not even support FOR loop. And by the way even command.com from MS-DOS 5.0 works fine in DOSBox.

On the other hand, echo ...|set /P VAR= seems to work only in FreeDOS command.com. In fact it also works in cmd.exe, but cmd.exe in order to provide parallel processing of data creates another copy of itself for all code after |, so the VAR is lost after returning from there.

**Comment by shidel** [comment]
You are absolutely correct. :-)

The tests were only meant to verify I/O redirection with SET /P support. Which is not supported under the built in DOSBox command shell. So, I reworked all of the examples to make that a little clearer and make some general improvements. 

If you wanted to test for DOSBox (regardless of command shell), you could do the following...

```
vinfo /m
if errorlevel 102 goto OtherEMU
if errorlevel 101 goto DOSBox
goto NotEMU
```
FreeDOS's FreeCOM in DOSBox... LOL, I do the same thing. :-)

Did you know that starting with FreeDOS 1.2, the installer (built on V8Power Tools) supports a semi-hybrid install specifically for DOSBox? Basically, it keeps the DOSBox kernel and sets it up with all of the FreeDOS tools and command shell. More info at [FDI - FreeDOS Installer](https://github.com/shidel/FDI).
