### ISSUE TITLE
ErrorCode usage.

### ISSUE THREAD

**Issue by Nable80** [LoopZ/V8Power#2]
Hi!
I was studying your code and I've noticed two strange things about ``ErrorCode`` variable that is defined in ``SOURCE/DSKTLS.INC``:

1. It's never read, there are only assignments to it (upd: at least I couldn't find any reads).
2. It's defined as a word (``dw``) but it's written as a byte (``mov [ErrorCode], al`` in one place and ``mov [cs:ErrorCode], al`` in another, one more strange difference).

Did I miss anything?
Thank you in advance.

**Comment by shidel** [comment]
Hi, 

You are correct. At present, nothing uses the value stored at `[cs:ErrorCode]` and only recently was `[cs:Critical]` added to note that the OS invoked the interrupt. This may change eventually and may be of use in future enhancements to some of the utilities. Mostly, this substitute
interrupt handler is used to prevent DOS from throwing up messages and prompting the user when probing the hard disk and file system.  

`dw` should be `db`. Also, there is no need to push/pop ax. Just some left overs from during initial development/testing of the routine. I should clean that up. 

As for referencing the value stored there as `[cs:ErrorCode]` and `[ErrorCode]`, there is a good reason. As you know, during execution CS points to the Code Segment and DS points Data Segment (normally). In a binary image (COM file) under DOS, these are the (usually) the same. CS = DS. So, `mov [ErrorCode], al` is similar to using `mov [ds:ErrorCode], al`. 

However, the `MyInt24` is an interrupt handler. It is invoked by the OS and not by the program. When the OS calls it, DS could be anything and probably points to the OS Kernel Data Segment. When that code is processed, the only known segment register is CS. So, we need to override the default segment with an explicit reference to out programs code segment by using `mov [cs:ErrorCode], al`. 

If the code there was longer, it would be easier to just reload or data segment into DS. Something like:

```
MyInt24:
     push ds
     push cs
     pop  ds
     mov  ax, di 
     mov  [ErrorCode] al
     pop  ds
     iret

```
I hope that explains why some are `[cs:ErrorCode]`  and some are just `[ErrorCode]`.

**Comment by Nable80** [comment]
Thank you very much for this detailed explanation!

> So, we need to override the default segment with an explicit reference to out programs code segment by using mov [cs:ErrorCode], al.

There's some irony here. Usage of CS segment override was completely understandable for me (this variable is definitely inside a code segment, not in a data one), while omission of it was questionable. Now I see that you're assuming a tiny/small memory model (CS = DS) and use this assumption to optimize out this segment prefix.

I think I can close this issue now. Does it make sense to leave it open for some time as a reminder for your clean-up plans?

**Comment by shidel** [comment]
Your welcome. Yup, tiny/small (CS= DS). 
Already cleaned that piece up. That being said... All of it needs cleaned up. It was written fast and loose with lots of spaghetti. With bits and pieces being created as they were needed by the FreeDOS installer, it more or less needed to "ship" before it was written.
